config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'


Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'

  authenticate :user do
    # upload, design and wizard
    resources :chat_uploads, only: %i[index new create destroy show] do
      resources :chat_designs, only: %i[index new create edit update destroy] do
        resources :wizard, controller: 'chat_designs/wizard', only: [:show, :create, :update]
        get 'wizards/', to: "chat_designs/wizard#create"
        get 'wizard/style_configuration/refresh_preview/', to: 'chat_designs/wizard#refresh_preview'
      end
      get 'chat_designs/:id/build_files/', to: 'chat_designs#build_files', as: 'chat_design_build_files'
      get 'chat_designs/:id/processing/', to: 'chat_designs#processing', as: 'chat_design_processing'
    end
    get 'chat_upload/:id/processing/', to: 'chat_uploads#processing', as: 'chat_upload_processing'

    # file download
    get '/files/tex_information/:chat_design_id', to: 'files#tex_information', as: 'file_information_tex'
    get '/files/download_tex/:chat_design_id', to: 'files#download_tex', as: 'file_download_tex'
    get '/files/download_pdf/:chat_design_id', to: 'files#download_pdf', as: 'file_download_pdf'

    # static pages
    get '/export_help/', to: 'static_pages#export_help', as: 'static_page_export_help'

  end

  # sidekiq ui
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # public routes
  get '/imprint/', to: 'static_pages#imprint', as: 'imprint'
  get '/privacy_policy/', to: 'static_pages#privacy_policy', as: 'privacy_policy'

end

app/models/chat_upload.rb
# frozen_string_literal: true

class ChatUpload < ApplicationRecord
  
  # scopes
  scope :existing, -> { where.not(processing_status: 'deleted') }
  
  # asscociations
  belongs_to :user
  has_many :chat_messages, dependent: :delete_all
  has_many :chat_designs, dependent: :delete_all

  # file associations
  has_one_attached :file_raw

  # enum declarations
  enum messenger_type: %i[whatsapp fbmessenger]
  enum processing_status: %i[processing success error deleted]

  #validations
  validates :name, presence: true
  validates :messenger_type, presence: true
  validate :file_raw_validation
  validates :user, presence: true
  validates :file_raw, blob: { content_type: ['application/json', 'text/plain'] }

  # instance methods
  def file_raw_validation
    errors[:file_raw] << 'No file selected' unless file_raw.attached?
  end

  def groupchat?
    chat_messages.where.not(sender: 'System').pluck(:sender).uniq.length > 2
  end

  def participants
    chat_messages.where.not(sender: 'System').pluck(:sender).uniq
  end

  def message_count
    chat_messages.count
  end
end

app/controllers/chat_uploads_controller.rb
# frozen_string_literal: true

class ChatUploadsController < ApplicationController
  def new
    @chat_upload = ChatUpload.new
    authorize @chat_upload
  end

  def create
    skip_authorization # does not need to be authorized
    result = ChatUploads::CreateService.new(chat_upload_params, current_user).execute
    if result.success?
      redirect_to chat_upload_processing_path(result.subject)
    else
      @chat_upload = result.subject
      flash[:alert] = "Error: " + result.error.to_s
      render 'new'
    end
  end

  def index
    # get upload from database
    @chat_uploads = policy_scope(ChatUpload).existing.order(:created_at)
    
    # for refreshing row in processing viw ajax the specific row is loaded
    @chat_upload_to_refresh = @chat_uploads.find(params[:refresh_id]) if params[:refresh_id].present?

    # paginate uploads and get current page
    @chat_uploads = @chat_uploads.page params[:page]
    @current_page = @chat_uploads.current_page

    respond_to do |format|
      format.js
      format.html
    end
  end

  def destroy
    @chat_upload = ChatUpload.find(params[:id])
    authorize @chat_upload

    # set deleted flag at upload
    @chat_upload.update(processing_status: :deleted)

    # call asynchronous worker for upload deleting
    UploadDestroyWorker.perform_async(@chat_upload.id, current_user.id)

    # notify user and redirect
    flash[:notice] = "Upload successfully deleted!"
    redirect_to chat_uploads_path
  end

  def processing
    @chat_upload = ChatUpload.find(params[:id])
    authorize @chat_upload

    # redirect to design creation when processing is complete
    # redirection when request comes via ajax
    render :js => "window.location = '/chat_uploads/#{@chat_upload.id}/chat_designs/build/wizards'" if request.xhr? && @chat_upload.success?
    # redirect if a user accesses the page for a finished upload
    redirect_to "/chat_uploads/#{@chat_upload.id}/chat_designs/build/wizards" if !request.xhr? && @chat_upload.success?

    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def chat_upload_params
    params.require(:chat_upload).permit(:name, :description, :messenger_type, :file_raw)
  end
end

app/helpers/chat_uploads_helper.rb
module ChatUploadsHelper
end

app/views/chat_uploads/_processing_view.html.haml
- if @chat_upload.processing?
  -# reload page every 5 seconds as long the upload processes
  :javascript
    $(document).ready(function () {
      setTimeout(refreshProcessingViewChatUploadPartial, 5000, #{@chat_upload.id});
    });
  %h3
    %span.fa.fa-spinner.fa-spin 
    Your Upload is currently being processed...
  You will be redirected, once this is finished.
  %br
  %br
  %br
  Depending on the number of messages this may take several minutes. 
  %br
  You do not have to wait, you can access your upload via 
  = link_to "My Uploads", chat_uploads_path
  at any time.
- if @chat_upload.error?
  %h3
    %span.fa.fa-times-circle
    An error occured while processing your upload.
  Make sure you have seleted the correct messenger type and try to upload your chat again.
  %br
  %br
  %br
  %h6 If the error persists, it is likely that your chat export is not processable...
  The export format is defined by the messenger's company and can be changed at any time, making 
  %br
  it unreadable for our system. Unfortunately we do not have any influence on that. Sorry!

app/views/chat_uploads/_row.html.haml
%td
  = chat_upload.created_at.strftime("%d/%m/%Y")
%td
  %span{data:{ toggle: "tooltip", placement: "right" }, title: chat_upload.description }
    = chat_upload.name
%td
  - if chat_upload.whatsapp?
    .fab.fa-whatsapp
  - else
    = icon('fab', 'facebook-messenger')  
  = ChatUpload.human_enum_name(:messenger_type, chat_upload.messenger_type)
  %span.badge.badge-success{data:{ toggle: "tooltip", placement: "top" }, title: "Messages in this upload" }
    = chat_upload.message_count
  - if chat_upload.groupchat?
    %span.badge.badge-secondary
      Group
%td
  - if chat_upload.processing?
    -# reload page every 5 seconds as long something processes
    :javascript
      $(document).ready(function () {
        setTimeout(refreshProcessingChatUploadPartial, 5000, #{chat_upload.id}, #{@current_page});
      });
    %span.fa.fa-spinner.fa-spin
    = t("processing", scope: :dict)
  - if chat_upload.success?
    %span.fa.fa-check-circle
    = t("success", scope: :dict)
  - if chat_upload.error?
    %div
      %span.fa.fa-times-circle
      = t("error", scope: :dict)
      (
      %a{ data: { toggle: "popover", content: chat_upload.processing_error.to_s, trigger: "focus", placement: "top" }, tabindex: '0', href: 'javascript:void(0);' }
        = t("details", scope: :dict)
      )
%td.text-right
  = link_to chat_upload_chat_designs_path(chat_upload), class: "btn btn-primary mr-2 #{ 'disabled' unless chat_upload.processing_status == "success" }" do
    = "Designs"
  -# = link_to "#", class: "btn btn-primary mr-2" do
  -#   = icon('fas', 'pencil-alt')
  = link_to chat_upload_path(chat_upload), method: :delete, data: { confirm: 'Are you sure you want to delete this Upload and all its Designs?' }, class: "btn btn-danger" do
    = icon('fas', 'trash-alt')

app/views/chat_uploads/_table.html.haml
%table.table.table-striped
  %thead
    %th 
      = t(".uploaded_at")
    %th 
      = t(".name")
    %th 
      = t(".messenger")
    %th
      = t("status", scope: :dict)
    %th.text-right 
      = t(".actions")
  %tbody
    - chat_uploads.each do |chat_upload|
      %tr{id: "chat-upload-row-#{chat_upload.id}"}
        = render "chat_uploads/row", chat_upload: chat_upload

app/views/chat_uploads/index.html.haml
.container
  .col-12
    %h1 
      =t(".my_uploaded_chats")
  .col-12.text-right.mt-2.mb-2
    = link_to new_chat_upload_path, class: "btn btn-secondary" do
      = icon('fas','plus')
      = t(".add_new_upload")
  .col-12.d-block
    #chat_uploads_table
      = render "table", chat_uploads: @chat_uploads
  - if !@chat_uploads.any?
    .row.mt-5
      .col-12.text-center
        It seems, that your do not have any uploads yet. Start uploading by clicking
        = link_to new_chat_upload_path do
          here
        \.
  - else
    .row.mt-3.justify-content-center
      .col-auto
        = paginate @chat_uploads

app/views/chat_uploads/index.js.haml
$('#chat-upload-row-#{@chat_upload_to_refresh.id}').html("#{escape_javascript(render 'chat_uploads/row', chat_upload: @chat_upload_to_refresh)}");

app/views/chat_uploads/new.html.haml
.container
  %h1 
    = t(".upload_new_chat_history")
  .jumbotron
    = simple_form_for @chat_upload do |f|
      .mb-3
        By filling in the information below, you can upload your chat export from WhatsApp and Facebook Messenger and create a beautiful design. Your data is send via encrypted connection and is stored savely. You can delete the upload at any time.
      = f.input :name, hint: "Choose a name for your Upload."
      = f.input :description, as: :text, hint: "Optional: Choose a description for your Upload."
      .row.mt-5.mb-5
        .col-12
          In the following section you have to choose the file, you want to upload, and the messenger this file was exported from. In case you are not sure how to export your history, please visit the
          = link_to static_page_export_help_path do
            .fa.fa-question-circle
            help page
          \.
      .row.mb-3
        .col-6
          = f.label :file_raw, label: "Messenger Export file"
          .alert{class: (@chat_upload.errors[:file_raw].present?) ? "alert-danger" : "alert-secondary" }
            = f.file_field :file_raw, label: "Chat History file"
            = f.error :file_raw
        .col-6
          = f.input :messenger_type, as: :select, collection: enum_option_pairs(ChatUpload, :messenger_type), hint: "Select your messenger."
      Once you click on upload your data will be processed in the background.
      %br
      = f.button :submit, "Upload", class: "btn btn-secondary mt-2"

app/views/chat_uploads/processing.html.haml
.vertical-center.text-center
  .container
    .row
      .col-12#processing-status
        = render "chat_uploads/processing_view"
    .row
      .col-12.mt-4
        = link_to "Back to Uploads", chat_uploads_path, class: "btn btn-secondary"

app/views/chat_uploads/processing.js.haml
$('#processing-status').html("#{escape_javascript(render 'chat_uploads/processing_view')}");