config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'


Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'

  authenticate :user do
    # upload, design and wizard
    resources :chat_uploads, only: %i[index new create destroy show] do
      resources :chat_designs, only: %i[index new create edit update destroy] do
        resources :wizard, controller: 'chat_designs/wizard', only: [:show, :create, :update]
        get 'wizards/', to: "chat_designs/wizard#create"
        get 'wizard/style_configuration/refresh_preview/', to: 'chat_designs/wizard#refresh_preview'
      end
      get 'chat_designs/:id/build_files/', to: 'chat_designs#build_files', as: 'chat_design_build_files'
      get 'chat_designs/:id/processing/', to: 'chat_designs#processing', as: 'chat_design_processing'
    end
    get 'chat_upload/:id/processing/', to: 'chat_uploads#processing', as: 'chat_upload_processing'

    # file download
    get '/files/tex_information/:chat_design_id', to: 'files#tex_information', as: 'file_information_tex'
    get '/files/download_tex/:chat_design_id', to: 'files#download_tex', as: 'file_download_tex'
    get '/files/download_pdf/:chat_design_id', to: 'files#download_pdf', as: 'file_download_pdf'

    # static pages
    get '/export_help/', to: 'static_pages#export_help', as: 'static_page_export_help'

  end

  # sidekiq ui
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # public routes
  get '/imprint/', to: 'static_pages#imprint', as: 'imprint'
  get '/privacy_policy/', to: 'static_pages#privacy_policy', as: 'privacy_policy'

end

app/models/chat_design.rb
# frozen_string_literal: true

class ChatDesign < ApplicationRecord

  #scopes
  scope :active, -> { where(status: 'active') }
  
  # associations
  belongs_to :chat_upload

  # file associations
  has_one_attached :tex_file
  has_one_attached :pdf_file

  # enum declaration
  enum processing_status: %i[inactive processing success error]
  enum page_size: %i[a4 a5]
  enum page_outline: %i[table_design flow_design bubbles_design]
  enum color_set: [:whatsapp, :pastel, :bright, :bootstrap, :instagram]
  enum font: %i[fira_sans chancery courier]

  # validation steps for wizard
  # step: create_design
  with_options if: :active_or_create_design? do |design|
    design.validates :name, presence: true
  end
  # step: basic_configuration
  with_options if: :active_or_basic_configuration? do |design|
    design.validates :my_user_name, presence: true
    design.validate :any_chat_messages_in_period
    # validates :period_from, presence: true
    # validates :period_to, presence: true
  end
  # step: style_configuration
  with_options if: :active_or_style_configuration? do |design|
    design.validates :page_size, presence: true
    design.validates :page_outline, presence: true
    design.validates :column_count, presence: true
    design.validates :font, presence: true
    design.validates :color_set, presence: true
  end

  # validation flags for wizard steps
  def active?
    status == 'active'
  end

  def active_or_create_design?
    status.include?('create_design') || active?
  end

  def active_or_basic_configuration?
    status.include?('basic_configuration') || active?
  end

  def active_or_style_configuration?
    status.include?('style_configuration') || active?
  end

  # custom validation for messages in selected time period
  def any_chat_messages_in_period
    errors[:period_from] << 'No messages in the selected period' unless chat_messages_in_period.any?
    errors[:period_to] << 'No messages in the selected period' unless chat_messages_in_period.any?
  end


  # build list of available bg_images
  def self.get_background_images
    bg_images = Dir.entries("latex/backgrounds/").sort
    bg_images.delete(".")
    bg_images.delete("..")
    bg_images.unshift("- none -")
    return bg_images
  end

  # returns the chat messages that are in the specified period
  def chat_messages_in_period
    if period_from.nil? && period_to.nil?
      messages = chat_upload.chat_messages.all
    elsif period_from.present? && period_to.nil?
      messages = chat_upload.chat_messages.where("timestamp >= ?", period_from)
    elsif period_from.nil? && period_to.present?
      messages = chat_upload.chat_messages.where("timestamp <= ?", period_to)
    elsif period_from.present? && period_to.present?
      messages = chat_upload.chat_messages.where(timestamp: (period_from..period_to))
    end
    # workaround for a problem with whatsapps timestamps do not include seconds
    # in order to show whatsapp messages in the correct order they have to ordered
    # by the time of their creation (file is processed line by line)
    # returns the correctly sorted version
    if chat_upload.whatsapp?
      messages.order(:created_at)
    else
      messages.order(:timestamp)
    end
  end
end

app/controllers/chat_designs/wizard_controller.rb
class ChatDesigns::WizardController < ApplicationController
  include Wicked::Wizard

  steps :create_design, :basic_configuration, :style_configuration
  
  def show
    @chat_design = ChatDesign.find(params[:chat_design_id])
    authorize @chat_design
    @chat_upload = @chat_design.chat_upload

    # wizard steps
    case steps
    when :create_design
      
    when :basic_configuration

    when :style_configuration

    end
    render_wizard
  end

  def update
    # writes to the intermediate object and sets status accordingly
    @chat_design = ChatDesign.find(params[:chat_design_id])
    authorize @chat_design
    @chat_upload = @chat_design.chat_upload
    params[:chat_design][:status] = step.to_s
    params[:chat_design][:status] = 'active' if step == steps.last
    params[:chat_design][:bg_image] = nil if params[:chat_design][:bg_image] == '- none -'
    @chat_design.update_attributes(chat_design_params)
    render_wizard @chat_design
  end

  def create
    # create an inital empty object to be completed by the wizard
    @chat_upload = ChatUpload.find(params[:chat_upload_id])
    authorize @chat_upload
    @chat_design = ChatDesign.create!(chat_upload: @chat_upload)
    # deletes the object, if it is not finished in one hour
    DesignWizardCleanupWorker.perform_in(60.minutes, @chat_design.id, current_user.id)
    redirect_to chat_upload_chat_design_wizard_path(@chat_upload, @chat_design, steps.first)
  end

  def refresh_preview
    # ajax refresh action: 
    # reads data from the selected customization options and loads data accordingly
    # in order to refresh the preview in the 3rd wizard step
    skip_authorization

    @element = params[:element]
    @value = params[:value]
    @columns = params[:columns]

    if @element == "color_set"
      @color_sets = Dir.entries("app/assets/images/preview_color_sets").sort
      @color_sets.delete('..')
      @color_sets.delete('.')
    end

    respond_to do |format|
      format.js
    end
  end

  private

  def chat_design_params
    params.require(:chat_design).permit(:name, :my_user_name, :period_from, :period_to, :page_size, :page_outline, :column_count, :color_set, :font, :bg_image, :chat_upload_id, :status)
  end

  # path the wizard redirects to after the last step is completed
  def finish_wizard_path
    chat_upload_chat_design_build_files_path(@chat_upload, @chat_design)
  end
end

app/controllers/chat_designs_controller.rb
# frozen_string_literal: true

class ChatDesignsController < ApplicationController
  def index
    skip_policy_scope # chat_upload is being authorized
    @chat_upload = ChatUpload.find(params[:chat_upload_id])
    authorize @chat_upload
    @chat_designs = ChatDesign.where(chat_upload: params[:chat_upload_id], status: :active).order(:created_at).page params[:page]
    @current_page = @chat_designs.current_page
    
    # for refreshing row in processing via ajax script the specific row is loaded
    @chat_design_to_refresh = @chat_upload.chat_designs.find(params[:refresh_id]) if params[:refresh_id].present?

    respond_to do |format|
      format.js
      format.html
    end
  end

  def new
    @chat_upload = ChatUpload.find(params[:chat_upload_id])
    authorize @chat_upload
    @chat_design = ChatDesign.new
  end

  def create
    @chat_upload = ChatUpload.find(params[:chat_upload_id])
    authorize @chat_upload
    @chat_design = @chat_upload.chat_designs.create(chat_design_params.merge(status: 'active'))
    if @chat_design.save
      redirect_to chat_upload_chat_design_build_files_path(@chat_upload, @chat_design)
    else
      render 'new'
    end
  end

  def edit
    @chat_upload = ChatUpload.find(params[:chat_upload_id])
    authorize @chat_upload
    @chat_design = @chat_upload.chat_designs.find(params[:id])
  end

  def update
    @chat_upload = ChatUpload.find(params[:chat_upload_id])
    authorize @chat_upload
    @chat_design = @chat_upload.chat_designs.find(params[:id])
    if @chat_design.update(chat_design_params)
      redirect_to chat_upload_chat_design_build_files_path(@chat_upload, @chat_design)
    else
      render 'edit'
    end
  end

  def destroy
    @chat_upload = ChatUpload.find(params[:chat_upload_id])
    authorize @chat_upload
    @chat_design = @chat_upload.chat_designs.find(params[:id])
    @chat_design.destroy

    flash[:notice] = t('.design_successfully_deleted')
    redirect_to chat_upload_chat_designs_path
  end

  def build_files
    # loads the chat design and calls the worker for file creation
    @chat_design = ChatDesign.find(params[:id])
    authorize @chat_design
    reset_processing_status
    LatexCreateWorker.perform_async(@chat_design.id, current_user.id)
    redirect_to chat_upload_chat_design_processing_path
  end


  def processing
    @chat_upload = ChatUpload.find(params[:chat_upload_id])
    authorize @chat_upload
    @chat_design = @chat_upload.chat_designs.find(params[:id])

    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def chat_design_params
    params.require(:chat_design).permit(:name, :my_user_name, :period_from, :period_to, :page_size, :page_outline, :column_count, :color_set, :font, :bg_image, :chat_upload_id)
  end

  # resets all processing attributes for a given ChatDesign
  def reset_processing_status
    @chat_design.update(processing_status: :processing)
    @chat_design.update(processing_error: nil)
    @chat_design.update(processing_progress: 0)
  end
end

app/helpers/chat_designs_helper.rb
module ChatDesignsHelper
end

app/views/chat_designs/_form.html.haml
= simple_form_for @chat_design, url: form_url do |f|
  .form_input
    .row
      .col-12.col-md-6  
        = f.input :name, hint: "Please select a name for your design", item_wrapper_class: "form-control"
    .row 
      .col-12.col-md-6
        = f.input :my_user_name, as: :select, collection: @chat_upload.participants, hint: "Please select your username from the chat"
      .col-12.col-md-3
        = f.input :period_from, as: :string, input_html: { class: 'datetime', value: (f.object.period_from.strftime("%d.%m.%Y %H:%M") if f.object.period_from.present?), autocomplete: 'off' }
      .col-12.col-md-3
        = f.input :period_to, as: :string, input_html:{ class: 'datetime', value: (f.object.period_to.strftime("%d.%m.%Y %H:%M") if f.object.period_to.present?), autocomplete: 'off' }
    .row
      .col-4
        = f.input :page_size, as: :select, collection: enum_option_pairs(ChatDesign,:page_size)
      .col-4
        = f.input :page_outline, as: :select, collection: enum_option_pairs(ChatDesign, :page_outline)
      .col-4
        = f.input :column_count, as: :radio_buttons, collection: 1..3, item_wrapper_class: "form-check form-check-inline"
    .row
      .col-4
        = f.input :color_set, as: :select, collection: ChatDesign.color_sets.keys
      .col-4
        = f.input :font, as: :select, collection: ChatDesign.fonts.keys
      .col-4
        = f.input :bg_image, as: :select, collection: ChatDesign.get_background_images
  
  .form-submit
    = f.button :submit, "Save", class: "btn btn-secondary"

app/views/chat_designs/_processing_status.html.haml
- if chat_design.processing_status == "processing"
  -# reload page every 5 seconds as long something processes
  :javascript
    $(document).ready(function () {
      setTimeout(refreshProcessingChatDesignPartial, 5000, #{chat_design.id}, #{@current_page});
    });
  .mt-1
    %span.progress{ style: "height: 20px; width: 120px;", data:{ toggle: "tooltip", placement: "top" }, title: "#{ chat_design.tex_file.attached? ? "Compiling PDF file with LaTeX..." : "Building TEX files..."}" }
      - if chat_design.tex_file.attached?
        .progress-bar.progress-bar-striped.progress-bar-animated.bg-success{style: "width: 100%"}
      - else
        .progress-bar.progress-bar-striped.progress-bar-animated{style: "width: #{chat_design.processing_progress}%"}
- if chat_design.processing_status == "success"
  %span.fa.fa-check-circle
  = t("success", scope: :dict)
- if chat_design.processing_status == "error"
  %div
    %span.fa.fa-times-circle
    = t("error", scope: :dict)
    (
    %a{ data: { toggle: "popover", content: chat_design.processing_error.to_s, trigger: "focus", placement: "top" }, tabindex: '0', href: 'javascript:void(0);' }
      = t("details", scope: :dict)
    )

app/views/chat_designs/_processing_view.html.haml
- if @chat_design.processing?
  -# reload page every 5 seconds as long the upload processes
  :javascript
    $(document).ready(function () {
      setTimeout(refreshProcessingViewChatDesignPartial, 5000, #{@chat_upload.id});
    });
.row
  .col-12.mb-4
    - if @chat_design.processing?
      .text-center
        %h4
          .fa.fa-spinner.fa-spin
          Preparing your Download...
        You can check the progress below. Depending on the length of your chat, this may take some time.
    - if @chat_design.success?
      .text-center
        %h4
          .fa.fa-check-circle
          Your files are ready to download.
        Click one of the links below.
    - if @chat_design.error?
      - if @chat_design.tex_file.attached? && !@chat_design.pdf_file.attached?
        .text-center
          %h4
            .fa.fa-info-circle
            Error in PDF creation.
          In some constellations, the PDF generation fails.
          You can download the TEX file and try to debug the error yourself.
      - else
        .text-center
          %h4
            .fa.fa-times-circle
            Error in file preparation.
          The file preparation failed. You can try a different design configuration. Edit & Save your Design to try again.
.row.row-eq-height
  .col-12.col-md-4
    .card.h-100.m-3
      .card-header
        .row
          .col-auto
            Design
          .col-auto.ml-auto
            .fa.fa-check-circle
      .card.m-3
        .list-group.list-group-flush
          .list-group-item.d-flex.justify-content-between.align-items-center
            Pagesize
            %span.badge.badge-secondary
              = ChatDesign.human_enum_name(:page_size, @chat_design.page_size)
          .list-group-item.d-flex.justify-content-between.align-items-center
            Design
            %span.badge.badge-secondary
              = ChatDesign.human_enum_name(:page_outline, @chat_design.page_outline)
          .list-group-item.d-flex.justify-content-between.align-items-center
            Columns
            %span.badge.badge-secondary
              = "#{@chat_design.column_count} columns"
          .list-group-item.d-flex.justify-content-between.align-items-center
            Colorset
            %span.badge.badge-secondary
              = ChatDesign.human_enum_name(:color_set, @chat_design.color_set)
          .list-group-item.d-flex.justify-content-between.align-items-center
            Font
            %span.badge.badge-secondary
              = ChatDesign.human_enum_name(:font, @chat_design.font)
      .card-body.pb-0.pt-0.bg-transparent.text-center{data:{ toggle: "tooltip", placement: "top" }, title: "#{'Design can not be edited or deleted while it is being processed.' if @chat_design.processing?}"}
        = link_to chat_upload_chat_design_wizard_path(@chat_design.chat_upload, @chat_design, :create_design), class: "btn btn-primary mr-2 #{'disabled' if @chat_design.processing?}" do
          = icon('fas', 'pen')
          Edit
        = link_to [@chat_design.chat_upload,@chat_design], method: :delete, class: "btn btn-danger #{'disabled' if @chat_design.processing?}" do
          = icon('fas', 'trash-alt')
          Delete
  .col-12.col-md-4
    .card.h-100.m-3
      .card-header.bg-secondary.text-white
        .row
          .col-auto
            TEX File
          .col-auto.ml-auto
            - if @chat_design.processing? && !@chat_design.tex_file.attached?
              .fa.fa-spinner.fa-spin
            - else
              - if @chat_design.tex_file.attached?
                .fa.fa-check-circle
              - else
                .fa.fa-times-circle
      .card-body
        .cade-text
          If you are familiar with LaTeX, you can download the TEX file of your Design. Hereby, you have to opportunity to customize your design even further by editing the file directly.
      .card-footer.bg-transparent.text-center
        - if !@chat_design.tex_file.attached?
          - if !@chat_design.processing?
            %span.progress{ style: "height: 20px;", data:{ toggle: "tooltip", placement: "top" }, title: ""}
              .progress-bar.progress-bar-striped.bg-danger{style: "width: 100%"}
                Error
          - else
            %span.progress{ style: "height: 20px;", data:{ toggle: "tooltip", placement: "top" }, title: "Building TEX files..."}
              .progress-bar.progress-bar-striped.progress-bar-animated.bg-secondary{style: "width: #{@chat_design.processing_progress}%"}
        - else
          - if @chat_design.tex_file.attached?
            = link_to file_information_tex_path(@chat_design), class: "btn btn-secondary mr-2 #{'disabled' unless @chat_design.tex_file.attached?}" do
              = icon('fas', 'download')
              Download TEX
  .col-12.col-md-4
    .card.h-100.m-3
      .card-header.bg-primary.text-white
        .row
          .col-auto
            PDF File
          .col-auto.ml-auto
            - if @chat_design.processing?
              .fa.fa-spinner.fa-spin
            - else
              - if @chat_design.pdf_file.attached?
                .fa.fa-check-circle
              - else
                .fa.fa-times-circle
      .card-body
        .card-text
          Your Design in PDF format. This format is perfect for printing and displaying on a screen. You can download the file by clicking on the link below.
      .card-footer.bg-transparent.text-center
        - if !@chat_design.processing? 
          - if @chat_design.pdf_file.attached?
            = link_to file_download_pdf_path(@chat_design), class: "btn btn-primary mr-2 #{'disabled' unless @chat_design.pdf_file.attached?}", target: "_blank" do
              = icon('fas', 'download')
              Download PDF
          - else
            %span.progress{ style: "height: 20px;", data:{ toggle: "tooltip", placement: "top" }, title: ""}
              .progress-bar.progress-bar-striped.bg-danger{style: "width: 100%"}
                Error
        - else
          - if !@chat_design.tex_file.attached?
            %span.progress{ style: "height: 20px;", data:{ toggle: "tooltip", placement: "top" }, title: ""}
              .progress-bar.progress-bar-striped{style: "width: 100%"}
                Waiting for TEX file...
          - else
            %span.progress{ style: "height: 20px;", data:{ toggle: "tooltip", placement: "top" }, title: "Compiling PDF..."}
              .progress-bar.progress-bar-striped.progress-bar-animated{style: "width: 100%"}

app/views/chat_designs/_row.html.haml
%td
  = chat_design.created_at.strftime("%d/%m/%Y")
%td
  = chat_design.name
%td
  - if chat_design.period_from.present? && chat_design.period_to.present?
    %span.badge.badge-secondary
      = chat_design.period_from.strftime("%d/%m/%y")
    \-
    %span.badge.badge-secondary
      = chat_design.period_to.strftime("%d/%m/%y")
  - else
    %span.badge.badge-secondary
      All Messages  
%td
  %span.badge.badge-secondary
    = ChatDesign.human_enum_name(:page_size, chat_design.page_size)
  %span.badge.badge-secondary
    = ChatDesign.human_enum_name(:page_outline, chat_design.page_outline)
%td
  = render "chat_designs/processing_status", chat_design: chat_design
%td.text-right
  = link_to chat_upload_chat_design_processing_path(chat_design.chat_upload, chat_design), class: "btn btn-primary" do
    = icon('fas', 'download')
  %span.p-0{data:{ toggle: "tooltip", placement: "top" }, title: "#{'Design can not be edited or deleted while it is being processed.' if chat_design.processing? }" }
    = link_to chat_upload_chat_design_wizard_path(chat_design.chat_upload, chat_design, :create_design), class: "btn btn-primary mr-1 #{'disabled' if chat_design.processing?}" do
      = icon('fas', 'pen')
    = link_to [chat_design.chat_upload,chat_design], method: :delete, class: "btn btn-danger #{'disabled' if chat_design.processing?}" do
      = icon('fas', 'trash-alt')

app/views/chat_designs/_table.html.haml
%table.table.table-striped
  %thead
    %th 
      = t(".created_at")
    %th 
      = t(".design_name")
    %th
      = t(".period")
    %th
      = t(".configuration")
    %th
      = t("status", scope: :dict)
    %th.text-right 
      = t(".actions")
  %tbody
    - chat_designs.each do |chat_design|
      %tr{id: "chat-design-row-#{chat_design.id}"}
        = render "chat_designs/row", chat_design: chat_design

app/views/chat_designs/edit.html.haml
.container
  %h1 
    = t(".edit_design")
  = render "form", form_url: :chat_upload_chat_design

app/views/chat_designs/index.html.haml
.container
  %h1.mb-4
    =t(".my_designs", chat_upload: @chat_upload.name)
  .row
    .col-auto.mt-2.mb-2
      = link_to chat_uploads_path, class: "btn btn-secondary" do
        = icon('fas','arrow-left')
        = t(".back_to_uploads")
    .col-auto.text-right.mt-2.mb-2.ml-auto.pr-0
      -# = link_to new_chat_upload_chat_design_path, class: "btn btn-secondary" do
      -#   = icon('fas','plus')
      -#   = t(".quick_add_design")
    .col-auto.text-right.mt-2.mb-2
      = link_to ("chat_designs/build/wizard/"), method: :post, class: "btn btn-secondary" do
        = icon('fas','plus')
        = t(".create_new_design")
    .col-12.d-block
      #table_body_rows
        = render "chat_designs/table", chat_designs: @chat_designs
  - if !@chat_designs.any?
    .row.mt-5
      .col-12.text-center
        It seems, that your do not have any designs for
        %b
          = @chat_upload.name
        yet. Start creating one by clicking
        = link_to ("chat_designs/build/wizard/"), method: :post do
          here
        \.
  - else
    .row.mt-3.justify-content-center
      .col-auto
        = paginate @chat_designs

app/views/chat_designs/index.js.haml
$('#chat-design-row-#{@chat_design_to_refresh.id}').html("#{escape_javascript(render 'chat_designs/row', chat_design: @chat_design_to_refresh)}");

app/views/chat_designs/new.html.haml
.container
  %h1 
    = t(".new_design")
  = render "form", form_url: :chat_upload_chat_designs

app/views/chat_designs/processing.html.haml
.container
  .jumbotron
    #processing-status
      = render "chat_designs/processing_view"
    .mt-5
      .col-12
        = link_to chat_upload_chat_designs_path, class: "btn btn-secondary" do
          = icon('fas','arrow-left')
          Back to Designs

app/views/chat_designs/processing.js.haml
$('#processing-status').html("#{escape_javascript(render 'chat_designs/processing_view')}");