config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'


Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#index'

  authenticate :user do
    # upload, design and wizard
    resources :chat_uploads, only: %i[index new create destroy show] do
      resources :chat_designs, only: %i[index new create edit update destroy] do
        resources :wizard, controller: 'chat_designs/wizard', only: [:show, :create, :update]
        get 'wizards/', to: "chat_designs/wizard#create"
        get 'wizard/style_configuration/refresh_preview/', to: 'chat_designs/wizard#refresh_preview'
      end
      get 'chat_designs/:id/build_files/', to: 'chat_designs#build_files', as: 'chat_design_build_files'
      get 'chat_designs/:id/processing/', to: 'chat_designs#processing', as: 'chat_design_processing'
    end
    get 'chat_upload/:id/processing/', to: 'chat_uploads#processing', as: 'chat_upload_processing'

    # file download
    get '/files/tex_information/:chat_design_id', to: 'files#tex_information', as: 'file_information_tex'
    get '/files/download_tex/:chat_design_id', to: 'files#download_tex', as: 'file_download_tex'
    get '/files/download_pdf/:chat_design_id', to: 'files#download_pdf', as: 'file_download_pdf'

    # static pages
    get '/export_help/', to: 'static_pages#export_help', as: 'static_page_export_help'

  end

  # sidekiq ui
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # public routes
  get '/imprint/', to: 'static_pages#imprint', as: 'imprint'
  get '/privacy_policy/', to: 'static_pages#privacy_policy', as: 'privacy_policy'

end

app/controllers/files_controller.rb
# frozen_string_literal: true

class FilesController < ApplicationController
  def download_tex
    # checks if design and upload can be acquired from the database
    return design_not_found unless ChatDesign.exists?(params[:chat_design_id])

    @chat_design = ChatDesign.find(params[:chat_design_id])
    return tex_file_not_found unless @chat_design.tex_file.attached?

    # checks if currently logged-in user is authorized to see the data
    authorize @chat_design

    # executes the archive generation service and offers result for download
    result = Files::ZipTexService.new(@chat_design, @user).execute
    if result.success?
      send_data(result.subject.read, filename: 'chat.zip', type: 'application/zip', disposition: 'attachment')
    else
      flash[:alert] = 'Error creating tex archive: ' + result.error.to_s
    end
  end

  def tex_information
    # checks if design and upload can be acquired from the database
    return design_not_found unless ChatDesign.exists?(params[:chat_design_id])

    @chat_design = ChatDesign.find(params[:chat_design_id])
    return tex_file_not_found unless @chat_design.tex_file.attached?

    # checks if currently logged-in user is authorized to see the data
    authorize @chat_design
  end

  def download_pdf
    # checks if design and upload can be acquired from the database
    return design_not_found unless ChatDesign.exists?(params[:chat_design_id])

    @chat_design = ChatDesign.find(params[:chat_design_id])
    return tex_file_not_found unless @chat_design.tex_file.attached?

    # checks if currently logged-in user is authorized to see the data
    authorize @chat_design

    # fetches the pdf file from active storage and offers it for download
    send_data(@chat_design.pdf_file.download, filename: 'chat.pdf', type: 'application/pdf', disposition: 'inline')
  end

  private

  def design_not_found
    flash[:alert] = 'Design not found.'
    redirect_to chat_uploads_path
  end

  def tex_file_not_found
    flash[:alert] = 'Tex-File not found. Try to save design to create it.'
    redirect_to chat_upload_chat_designs_path(@chat_design.chat_upload)
  end
end

app/helpers/files_helper.rb
module FilesHelper
end

app/views/files/tex_information.html.haml
.container
  .col-12.d-flex.justify-content-center
    .col-12.col-md-6
      .card
        .card-header
          Download Tex-Archive
        .card-body
          You are about to download all LaTeX-files related to your design. This gives you the opportunity
          to customize your chat history even more.
          %br
          %br
          In order to compile the downloaded files you need
          %ul
            %li a distribution of tex-live 2016 (full)
            %li a LaTeX editor (e.g. Tex-Works)
            %li 
              the 
              %b 
                %a{href: "https://github.com/henningpohl/latex-emoji", target: "_blank"}
                  latex_emoji package
          If you have problems, installing custom packages for your LaTeX distribution, consult the tex-live documentation and follow the instructions provided
          %a{href: "https://tex.stackexchange.com/questions/73016/how-do-i-install-an-individual-package-on-a-linux-system", target: "_blank"}
            %b here
          \.
          %br
          %br
          Happy hacking!
          .mt-3
            = link_to file_download_tex_path(@chat_design), class: "btn btn-primary mr-2 #{'disabled' unless @chat_design.tex_file.attached?}" do
              = icon('fas', 'file-alt')
              = t(".download_tex_files")
              - if !@chat_design.tex_file.attached? && @chat_design.processing_status == "processing"
                %span.fa.fa-spinner.fa-spin
      = link_to chat_upload_chat_designs_path(@chat_design.chat_upload), class: "btn btn-secondary mt-3" do
        .fa.fa-arrow-left
        Back to Designs
      